// Học Tiếng Anh — Flashcard Lớp 1–5
// Dữ liệu sinh từ bộ từ vựng markdown (lop-1 … lop-5). Mỗi "day" = 1 chủ đề, nhóm theo level (Lớp).
// Mỗi card: { emoji, word, ipa, meaning }

const LESSONS = [
  // ===================== LỚP 1 =====================
  {
    id: 1, level: "Lớp 1", theme: "Màu sắc", themeEn: "Colors",
    cards: [
      { emoji: "🔴", word: "red", ipa: "/red/", meaning: "màu đỏ" },
      { emoji: "🔵", word: "blue", ipa: "/bluː/", meaning: "màu xanh dương" },
      { emoji: "🟡", word: "yellow", ipa: "/ˈjeləʊ/", meaning: "màu vàng" },
      { emoji: "🟢", word: "green", ipa: "/ɡriːn/", meaning: "màu xanh lá" },
      { emoji: "🟠", word: "orange", ipa: "/ˈɒrɪndʒ/", meaning: "màu cam" },
      { emoji: "🟣", word: "purple", ipa: "/ˈpɜːpl/", meaning: "màu tím" },
      { emoji: "🩷", word: "pink", ipa: "/pɪŋk/", meaning: "màu hồng" },
      { emoji: "⚫", word: "black", ipa: "/blæk/", meaning: "màu đen" },
      { emoji: "⚪", word: "white", ipa: "/waɪt/", meaning: "màu trắng" },
      { emoji: "🟤", word: "brown", ipa: "/braʊn/", meaning: "màu nâu" },
      { emoji: "🩶", word: "grey", ipa: "/ɡreɪ/", meaning: "màu xám" },
      { emoji: "🌈", word: "rainbow", ipa: "/ˈreɪnbəʊ/", meaning: "cầu vồng" },
      { emoji: "🥇", word: "gold", ipa: "/ɡəʊld/", meaning: "màu vàng kim" },
      { emoji: "🥈", word: "silver", ipa: "/ˈsɪlvə/", meaning: "màu bạc" },
    ],
  },
  {
    id: 2, level: "Lớp 1", theme: "Số đếm", themeEn: "Numbers",
    cards: [
      { emoji: "1️⃣", word: "one", ipa: "/wʌn/", meaning: "một" },
      { emoji: "2️⃣", word: "two", ipa: "/tuː/", meaning: "hai" },
      { emoji: "3️⃣", word: "three", ipa: "/θriː/", meaning: "ba" },
      { emoji: "4️⃣", word: "four", ipa: "/fɔː/", meaning: "bốn" },
      { emoji: "5️⃣", word: "five", ipa: "/faɪv/", meaning: "năm" },
      { emoji: "6️⃣", word: "six", ipa: "/sɪks/", meaning: "sáu" },
      { emoji: "7️⃣", word: "seven", ipa: "/ˈsevn/", meaning: "bảy" },
      { emoji: "8️⃣", word: "eight", ipa: "/eɪt/", meaning: "tám" },
      { emoji: "9️⃣", word: "nine", ipa: "/naɪn/", meaning: "chín" },
      { emoji: "🔟", word: "ten", ipa: "/ten/", meaning: "mười" },
      { emoji: "🕚", word: "eleven", ipa: "/ɪˈlevn/", meaning: "mười một" },
      { emoji: "🕛", word: "twelve", ipa: "/twelv/", meaning: "mười hai" },
      { emoji: "💯", word: "hundred", ipa: "/ˈhʌndrəd/", meaning: "một trăm" },
      { emoji: "0️⃣", word: "zero", ipa: "/ˈzɪərəʊ/", meaning: "số không" },
    ],
  },
  {
    id: 3, level: "Lớp 1", theme: "Trái cây", themeEn: "Fruits",
    cards: [
      { emoji: "🍎", word: "apple", ipa: "/ˈæpl/", meaning: "quả táo" },
      { emoji: "🍌", word: "banana", ipa: "/bəˈnɑːnə/", meaning: "quả chuối" },
      { emoji: "🍊", word: "orange", ipa: "/ˈɒrɪndʒ/", meaning: "quả cam" },
      { emoji: "🍓", word: "strawberry", ipa: "/ˈstrɔːbəri/", meaning: "quả dâu tây" },
      { emoji: "🍇", word: "grape", ipa: "/ɡreɪp/", meaning: "quả nho" },
      { emoji: "🍉", word: "watermelon", ipa: "/ˈwɔːtəmelən/", meaning: "quả dưa hấu" },
      { emoji: "🍍", word: "pineapple", ipa: "/ˈpaɪnæpl/", meaning: "quả dứa" },
      { emoji: "🥭", word: "mango", ipa: "/ˈmæŋɡəʊ/", meaning: "quả xoài" },
      { emoji: "🍑", word: "peach", ipa: "/piːtʃ/", meaning: "quả đào" },
      { emoji: "🍒", word: "cherry", ipa: "/ˈtʃeri/", meaning: "quả anh đào" },
      { emoji: "🍐", word: "pear", ipa: "/peə/", meaning: "quả lê" },
      { emoji: "🥝", word: "kiwi", ipa: "/ˈkiːwiː/", meaning: "quả kiwi" },
      { emoji: "🍋", word: "lemon", ipa: "/ˈlemən/", meaning: "quả chanh" },
      { emoji: "🥥", word: "coconut", ipa: "/ˈkəʊkənʌt/", meaning: "quả dừa" },
    ],
  },
  {
    id: 4, level: "Lớp 1", theme: "Động vật", themeEn: "Animals",
    cards: [
      { emoji: "🐶", word: "dog", ipa: "/dɒɡ/", meaning: "con chó" },
      { emoji: "🐱", word: "cat", ipa: "/kæt/", meaning: "con mèo" },
      { emoji: "🐭", word: "mouse", ipa: "/maʊs/", meaning: "con chuột" },
      { emoji: "🐰", word: "rabbit", ipa: "/ˈræbɪt/", meaning: "con thỏ" },
      { emoji: "🐻", word: "bear", ipa: "/beə/", meaning: "con gấu" },
      { emoji: "🐼", word: "panda", ipa: "/ˈpændə/", meaning: "gấu trúc" },
      { emoji: "🐯", word: "tiger", ipa: "/ˈtaɪɡə/", meaning: "con hổ" },
      { emoji: "🦁", word: "lion", ipa: "/ˈlaɪən/", meaning: "con sư tử" },
      { emoji: "🐘", word: "elephant", ipa: "/ˈelɪfənt/", meaning: "con voi" },
      { emoji: "🐷", word: "pig", ipa: "/pɪɡ/", meaning: "con lợn" },
      { emoji: "🐮", word: "cow", ipa: "/kaʊ/", meaning: "con bò" },
      { emoji: "🐔", word: "chicken", ipa: "/ˈtʃɪkɪn/", meaning: "con gà" },
      { emoji: "🐟", word: "fish", ipa: "/fɪʃ/", meaning: "con cá" },
      { emoji: "🐸", word: "frog", ipa: "/frɒɡ/", meaning: "con ếch" },
      { emoji: "🐦", word: "bird", ipa: "/bɜːd/", meaning: "con chim" },
    ],
  },
  {
    id: 5, level: "Lớp 1", theme: "Đồ dùng học tập", themeEn: "School Things",
    cards: [
      { emoji: "✏️", word: "pencil", ipa: "/ˈpensl/", meaning: "bút chì" },
      { emoji: "🖊️", word: "pen", ipa: "/pen/", meaning: "bút mực" },
      { emoji: "📓", word: "notebook", ipa: "/ˈnəʊtbʊk/", meaning: "quyển vở" },
      { emoji: "📖", word: "book", ipa: "/bʊk/", meaning: "quyển sách" },
      { emoji: "🎒", word: "bag", ipa: "/bæɡ/", meaning: "cặp sách" },
      { emoji: "📏", word: "ruler", ipa: "/ˈruːlə/", meaning: "thước kẻ" },
      { emoji: "✂️", word: "scissors", ipa: "/ˈsɪzəz/", meaning: "cái kéo" },
      { emoji: "🧽", word: "eraser", ipa: "/ɪˈreɪzə/", meaning: "cục tẩy" },
      { emoji: "🖍️", word: "crayon", ipa: "/ˈkreɪən/", meaning: "bút sáp màu" },
      { emoji: "🪟", word: "desk", ipa: "/desk/", meaning: "bàn học" },
      { emoji: "🪑", word: "chair", ipa: "/tʃeə/", meaning: "cái ghế" },
      { emoji: "🗒️", word: "paper", ipa: "/ˈpeɪpə/", meaning: "tờ giấy" },
      { emoji: "🖌️", word: "brush", ipa: "/brʌʃ/", meaning: "cây cọ" },
      { emoji: "🎨", word: "paint", ipa: "/peɪnt/", meaning: "màu vẽ" },
    ],
  },
  {
    id: 6, level: "Lớp 1", theme: "Cơ thể", themeEn: "Body",
    cards: [
      { emoji: "🧑", word: "head", ipa: "/hed/", meaning: "cái đầu" },
      { emoji: "💇", word: "hair", ipa: "/heə/", meaning: "tóc" },
      { emoji: "👁️", word: "eye", ipa: "/aɪ/", meaning: "mắt" },
      { emoji: "👂", word: "ear", ipa: "/ɪə/", meaning: "tai" },
      { emoji: "👃", word: "nose", ipa: "/nəʊz/", meaning: "mũi" },
      { emoji: "👄", word: "mouth", ipa: "/maʊθ/", meaning: "miệng" },
      { emoji: "🦷", word: "tooth", ipa: "/tuːθ/", meaning: "răng" },
      { emoji: "✋", word: "hand", ipa: "/hænd/", meaning: "bàn tay" },
      { emoji: "👆", word: "finger", ipa: "/ˈfɪŋɡə/", meaning: "ngón tay" },
      { emoji: "🦵", word: "leg", ipa: "/leɡ/", meaning: "chân" },
      { emoji: "🦶", word: "foot", ipa: "/fʊt/", meaning: "bàn chân" },
      { emoji: "💪", word: "arm", ipa: "/ɑːm/", meaning: "cánh tay" },
      { emoji: "😊", word: "face", ipa: "/feɪs/", meaning: "khuôn mặt" },
      { emoji: "🫀", word: "heart", ipa: "/hɑːt/", meaning: "trái tim" },
    ],
  },
  {
    id: 7, level: "Lớp 1", theme: "Gia đình", themeEn: "Family",
    cards: [
      { emoji: "👨", word: "father", ipa: "/ˈfɑːðə/", meaning: "bố" },
      { emoji: "👩", word: "mother", ipa: "/ˈmʌðə/", meaning: "mẹ" },
      { emoji: "👦", word: "brother", ipa: "/ˈbrʌðə/", meaning: "anh/em trai" },
      { emoji: "👧", word: "sister", ipa: "/ˈsɪstə/", meaning: "chị/em gái" },
      { emoji: "👶", word: "baby", ipa: "/ˈbeɪbi/", meaning: "em bé" },
      { emoji: "👴", word: "grandfather", ipa: "/ˈɡrænfɑːðə/", meaning: "ông" },
      { emoji: "👵", word: "grandmother", ipa: "/ˈɡrænmʌðə/", meaning: "bà" },
      { emoji: "👨‍👩‍👧", word: "family", ipa: "/ˈfæməli/", meaning: "gia đình" },
      { emoji: "🧔", word: "dad", ipa: "/dæd/", meaning: "ba (thân mật)" },
      { emoji: "👩‍🦰", word: "mum", ipa: "/mʌm/", meaning: "má (thân mật)" },
      { emoji: "🧒", word: "son", ipa: "/sʌn/", meaning: "con trai" },
      { emoji: "👧🏻", word: "daughter", ipa: "/ˈdɔːtə/", meaning: "con gái" },
      { emoji: "👨‍🦱", word: "uncle", ipa: "/ˈʌŋkl/", meaning: "chú/bác/cậu" },
      { emoji: "👩‍🦳", word: "aunt", ipa: "/ɑːnt/", meaning: "cô/dì/thím" },
    ],
  },
  // ===================== LỚP 2 =====================
  {
    id: 1, level: "Lớp 2", theme: "Rau củ", themeEn: "Vegetables",
    cards: [
      { emoji: "🥕", word: "carrot", ipa: "/ˈkærət/", meaning: "củ cà rốt" },
      { emoji: "🍅", word: "tomato", ipa: "/təˈmɑːtəʊ/", meaning: "cà chua" },
      { emoji: "🥔", word: "potato", ipa: "/pəˈteɪtəʊ/", meaning: "khoai tây" },
      { emoji: "🧅", word: "onion", ipa: "/ˈʌnjən/", meaning: "hành tây" },
      { emoji: "🥦", word: "broccoli", ipa: "/ˈbrɒkəli/", meaning: "bông cải xanh" },
      { emoji: "🌽", word: "corn", ipa: "/kɔːn/", meaning: "bắp ngô" },
      { emoji: "🥒", word: "cucumber", ipa: "/ˈkjuːkʌmbə/", meaning: "dưa chuột" },
      { emoji: "🍆", word: "eggplant", ipa: "/ˈeɡplɑːnt/", meaning: "cà tím" },
      { emoji: "🥬", word: "cabbage", ipa: "/ˈkæbɪdʒ/", meaning: "bắp cải" },
      { emoji: "🍄", word: "mushroom", ipa: "/ˈmʌʃrʊm/", meaning: "nấm" },
      { emoji: "🫑", word: "pepper", ipa: "/ˈpepə/", meaning: "ớt chuông" },
      { emoji: "🧄", word: "garlic", ipa: "/ˈɡɑːlɪk/", meaning: "tỏi" },
      { emoji: "🥗", word: "salad", ipa: "/ˈsæləd/", meaning: "salad rau" },
      { emoji: "🫛", word: "pea", ipa: "/piː/", meaning: "hạt đậu" },
    ],
  },
  {
    id: 2, level: "Lớp 2", theme: "Đồ vật trong nhà", themeEn: "Household Objects",
    cards: [
      { emoji: "🛏️", word: "bed", ipa: "/bed/", meaning: "cái giường" },
      { emoji: "🪑", word: "chair", ipa: "/tʃeə/", meaning: "cái ghế" },
      { emoji: "🍽️", word: "table", ipa: "/ˈteɪbl/", meaning: "cái bàn" },
      { emoji: "📺", word: "television", ipa: "/ˈtelɪvɪʒn/", meaning: "tivi" },
      { emoji: "🕰️", word: "clock", ipa: "/klɒk/", meaning: "đồng hồ" },
      { emoji: "🚪", word: "door", ipa: "/dɔː/", meaning: "cánh cửa" },
      { emoji: "🪟", word: "window", ipa: "/ˈwɪndəʊ/", meaning: "cửa sổ" },
      { emoji: "💡", word: "lamp", ipa: "/læmp/", meaning: "đèn" },
      { emoji: "🛋️", word: "sofa", ipa: "/ˈsəʊfə/", meaning: "ghế sô-pha" },
      { emoji: "🪞", word: "mirror", ipa: "/ˈmɪrə/", meaning: "cái gương" },
      { emoji: "🧹", word: "broom", ipa: "/bruːm/", meaning: "cây chổi" },
      { emoji: "🍴", word: "plate", ipa: "/pleɪt/", meaning: "cái đĩa" },
      { emoji: "🥄", word: "spoon", ipa: "/spuːn/", meaning: "cái thìa" },
      { emoji: "🔑", word: "key", ipa: "/kiː/", meaning: "chìa khóa" },
    ],
  },
  {
    id: 3, level: "Lớp 2", theme: "Phòng ốc", themeEn: "Rooms",
    cards: [
      { emoji: "🏠", word: "house", ipa: "/haʊs/", meaning: "ngôi nhà" },
      { emoji: "🛏️", word: "bedroom", ipa: "/ˈbedruːm/", meaning: "phòng ngủ" },
      { emoji: "🍳", word: "kitchen", ipa: "/ˈkɪtʃɪn/", meaning: "nhà bếp" },
      { emoji: "🛁", word: "bathroom", ipa: "/ˈbɑːθruːm/", meaning: "phòng tắm" },
      { emoji: "🛋️", word: "living room", ipa: "/ˈlɪvɪŋ ruːm/", meaning: "phòng khách" },
      { emoji: "🍽️", word: "dining room", ipa: "/ˈdaɪnɪŋ ruːm/", meaning: "phòng ăn" },
      { emoji: "🏛️", word: "hall", ipa: "/hɔːl/", meaning: "hành lang" },
      { emoji: "🪜", word: "stairs", ipa: "/steəz/", meaning: "cầu thang" },
      { emoji: "🏡", word: "garden", ipa: "/ˈɡɑːdn/", meaning: "khu vườn" },
      { emoji: "🚗", word: "garage", ipa: "/ˈɡærɑːʒ/", meaning: "nhà để xe" },
      { emoji: "🏢", word: "floor", ipa: "/flɔː/", meaning: "tầng/sàn" },
      { emoji: "🧱", word: "wall", ipa: "/wɔːl/", meaning: "bức tường" },
      { emoji: "🛖", word: "roof", ipa: "/ruːf/", meaning: "mái nhà" },
      { emoji: "🚪", word: "room", ipa: "/ruːm/", meaning: "căn phòng" },
    ],
  },
  {
    id: 4, level: "Lớp 2", theme: "Thời tiết", themeEn: "Weather",
    cards: [
      { emoji: "☀️", word: "sunny", ipa: "/ˈsʌni/", meaning: "nắng" },
      { emoji: "🌧️", word: "rainy", ipa: "/ˈreɪni/", meaning: "mưa" },
      { emoji: "☁️", word: "cloudy", ipa: "/ˈklaʊdi/", meaning: "nhiều mây" },
      { emoji: "❄️", word: "snowy", ipa: "/ˈsnəʊi/", meaning: "có tuyết" },
      { emoji: "💨", word: "windy", ipa: "/ˈwɪndi/", meaning: "có gió" },
      { emoji: "🌫️", word: "foggy", ipa: "/ˈfɒɡi/", meaning: "có sương mù" },
      { emoji: "⛈️", word: "stormy", ipa: "/ˈstɔːmi/", meaning: "có bão" },
      { emoji: "🌈", word: "rainbow", ipa: "/ˈreɪnbəʊ/", meaning: "cầu vồng" },
      { emoji: "🔥", word: "hot", ipa: "/hɒt/", meaning: "nóng" },
      { emoji: "🥶", word: "cold", ipa: "/kəʊld/", meaning: "lạnh" },
      { emoji: "🌡️", word: "warm", ipa: "/wɔːm/", meaning: "ấm áp" },
      { emoji: "💧", word: "rain", ipa: "/reɪn/", meaning: "mưa" },
      { emoji: "⛅", word: "sky", ipa: "/skaɪ/", meaning: "bầu trời" },
      { emoji: "🌪️", word: "wind", ipa: "/wɪnd/", meaning: "gió" },
    ],
  },
  {
    id: 5, level: "Lớp 2", theme: "Quần áo", themeEn: "Clothes",
    cards: [
      { emoji: "👕", word: "shirt", ipa: "/ʃɜːt/", meaning: "áo sơ mi" },
      { emoji: "👖", word: "trousers", ipa: "/ˈtraʊzəz/", meaning: "quần dài" },
      { emoji: "👗", word: "dress", ipa: "/dres/", meaning: "váy đầm" },
      { emoji: "🧥", word: "coat", ipa: "/kəʊt/", meaning: "áo khoác" },
      { emoji: "🧦", word: "socks", ipa: "/sɒks/", meaning: "tất/vớ" },
      { emoji: "👟", word: "shoes", ipa: "/ʃuːz/", meaning: "giày" },
      { emoji: "🧢", word: "cap", ipa: "/kæp/", meaning: "mũ lưỡi trai" },
      { emoji: "🎩", word: "hat", ipa: "/hæt/", meaning: "mũ" },
      { emoji: "🧤", word: "gloves", ipa: "/ɡlʌvz/", meaning: "găng tay" },
      { emoji: "🧣", word: "scarf", ipa: "/skɑːf/", meaning: "khăn quàng" },
      { emoji: "👚", word: "skirt", ipa: "/skɜːt/", meaning: "chân váy" },
      { emoji: "🩳", word: "shorts", ipa: "/ʃɔːts/", meaning: "quần soóc" },
      { emoji: "👔", word: "tie", ipa: "/taɪ/", meaning: "cà vạt" },
      { emoji: "🦺", word: "jacket", ipa: "/ˈdʒækɪt/", meaning: "áo khoác ngắn" },
    ],
  },
  {
    id: 6, level: "Lớp 2", theme: "Đồ ăn", themeEn: "Food",
    cards: [
      { emoji: "🍚", word: "rice", ipa: "/raɪs/", meaning: "cơm" },
      { emoji: "🍞", word: "bread", ipa: "/bred/", meaning: "bánh mì" },
      { emoji: "🥚", word: "egg", ipa: "/eɡ/", meaning: "trứng" },
      { emoji: "🥛", word: "milk", ipa: "/mɪlk/", meaning: "sữa" },
      { emoji: "🧀", word: "cheese", ipa: "/tʃiːz/", meaning: "phô mai" },
      { emoji: "🍜", word: "noodles", ipa: "/ˈnuːdlz/", meaning: "mì/bún" },
      { emoji: "🍗", word: "chicken", ipa: "/ˈtʃɪkɪn/", meaning: "thịt gà" },
      { emoji: "🐟", word: "fish", ipa: "/fɪʃ/", meaning: "cá (món ăn)" },
      { emoji: "🍰", word: "cake", ipa: "/keɪk/", meaning: "bánh ngọt" },
      { emoji: "🍪", word: "cookie", ipa: "/ˈkʊki/", meaning: "bánh quy" },
      { emoji: "🍦", word: "ice cream", ipa: "/ˈaɪs kriːm/", meaning: "kem" },
      { emoji: "🍲", word: "soup", ipa: "/suːp/", meaning: "súp/canh" },
      { emoji: "🍬", word: "candy", ipa: "/ˈkændi/", meaning: "kẹo" },
      { emoji: "💧", word: "water", ipa: "/ˈwɔːtə/", meaning: "nước" },
    ],
  },
  {
    id: 7, level: "Lớp 2", theme: "Hình dạng", themeEn: "Shapes",
    cards: [
      { emoji: "⭕", word: "circle", ipa: "/ˈsɜːkl/", meaning: "hình tròn" },
      { emoji: "🟥", word: "square", ipa: "/skweə/", meaning: "hình vuông" },
      { emoji: "🔺", word: "triangle", ipa: "/ˈtraɪæŋɡl/", meaning: "hình tam giác" },
      { emoji: "🟦", word: "rectangle", ipa: "/ˈrektæŋɡl/", meaning: "hình chữ nhật" },
      { emoji: "⭐", word: "star", ipa: "/stɑː/", meaning: "hình ngôi sao" },
      { emoji: "❤️", word: "heart", ipa: "/hɑːt/", meaning: "hình trái tim" },
      { emoji: "🔶", word: "diamond", ipa: "/ˈdaɪəmənd/", meaning: "hình thoi" },
      { emoji: "🥚", word: "oval", ipa: "/ˈəʊvl/", meaning: "hình bầu dục" },
      { emoji: "➖", word: "line", ipa: "/laɪn/", meaning: "đường thẳng" },
      { emoji: "🔵", word: "round", ipa: "/raʊnd/", meaning: "tròn" },
      { emoji: "📏", word: "flat", ipa: "/flæt/", meaning: "phẳng" },
      { emoji: "⬛", word: "big", ipa: "/bɪɡ/", meaning: "to/lớn" },
      { emoji: "▪️", word: "small", ipa: "/smɔːl/", meaning: "nhỏ" },
      { emoji: "🧊", word: "cube", ipa: "/kjuːb/", meaning: "hình lập phương" },
    ],
  },
  // ===================== LỚP 3 =====================
  {
    id: 1, level: "Lớp 3", theme: "Nghề nghiệp", themeEn: "Jobs",
    cards: [
      { emoji: "👨‍🏫", word: "teacher", ipa: "/ˈtiːtʃə/", meaning: "giáo viên" },
      { emoji: "👨‍⚕️", word: "doctor", ipa: "/ˈdɒktə/", meaning: "bác sĩ" },
      { emoji: "👮", word: "police officer", ipa: "/pəˈliːs ˈɒfɪsə/", meaning: "cảnh sát" },
      { emoji: "👨‍🚒", word: "firefighter", ipa: "/ˈfaɪəfaɪtə/", meaning: "lính cứu hỏa" },
      { emoji: "👨‍🌾", word: "farmer", ipa: "/ˈfɑːmə/", meaning: "nông dân" },
      { emoji: "👨‍🍳", word: "cook", ipa: "/kʊk/", meaning: "đầu bếp" },
      { emoji: "👨‍✈️", word: "pilot", ipa: "/ˈpaɪlət/", meaning: "phi công" },
      { emoji: "👩‍⚕️", word: "nurse", ipa: "/nɜːs/", meaning: "y tá" },
      { emoji: "👷", word: "worker", ipa: "/ˈwɜːkə/", meaning: "công nhân" },
      { emoji: "🎤", word: "singer", ipa: "/ˈsɪŋə/", meaning: "ca sĩ" },
      { emoji: "🧑‍🔧", word: "mechanic", ipa: "/məˈkænɪk/", meaning: "thợ máy" },
      { emoji: "🦷", word: "dentist", ipa: "/ˈdentɪst/", meaning: "nha sĩ" },
      { emoji: "🧑‍🎨", word: "painter", ipa: "/ˈpeɪntə/", meaning: "họa sĩ" },
      { emoji: "📮", word: "postman", ipa: "/ˈpəʊstmən/", meaning: "người đưa thư" },
    ],
  },
  {
    id: 2, level: "Lớp 3", theme: "Phương tiện", themeEn: "Vehicles",
    cards: [
      { emoji: "🚗", word: "car", ipa: "/kɑː/", meaning: "ô tô" },
      { emoji: "🚌", word: "bus", ipa: "/bʌs/", meaning: "xe buýt" },
      { emoji: "🚲", word: "bicycle", ipa: "/ˈbaɪsɪkl/", meaning: "xe đạp" },
      { emoji: "🏍️", word: "motorbike", ipa: "/ˈməʊtəbaɪk/", meaning: "xe máy" },
      { emoji: "🚂", word: "train", ipa: "/treɪn/", meaning: "tàu hỏa" },
      { emoji: "✈️", word: "plane", ipa: "/pleɪn/", meaning: "máy bay" },
      { emoji: "🚢", word: "ship", ipa: "/ʃɪp/", meaning: "tàu thủy" },
      { emoji: "🚁", word: "helicopter", ipa: "/ˈhelɪkɒptə/", meaning: "trực thăng" },
      { emoji: "🚕", word: "taxi", ipa: "/ˈtæksi/", meaning: "xe taxi" },
      { emoji: "🚚", word: "truck", ipa: "/trʌk/", meaning: "xe tải" },
      { emoji: "🚑", word: "ambulance", ipa: "/ˈæmbjələns/", meaning: "xe cứu thương" },
      { emoji: "⛵", word: "boat", ipa: "/bəʊt/", meaning: "thuyền" },
      { emoji: "🚀", word: "rocket", ipa: "/ˈrɒkɪt/", meaning: "tên lửa" },
      { emoji: "🛴", word: "scooter", ipa: "/ˈskuːtə/", meaning: "xe trượt scooter" },
    ],
  },
  {
    id: 3, level: "Lớp 3", theme: "Địa điểm", themeEn: "Places",
    cards: [
      { emoji: "🏫", word: "school", ipa: "/skuːl/", meaning: "trường học" },
      { emoji: "🏥", word: "hospital", ipa: "/ˈhɒspɪtl/", meaning: "bệnh viện" },
      { emoji: "🏪", word: "shop", ipa: "/ʃɒp/", meaning: "cửa hàng" },
      { emoji: "🏞️", word: "park", ipa: "/pɑːk/", meaning: "công viên" },
      { emoji: "🏦", word: "bank", ipa: "/bæŋk/", meaning: "ngân hàng" },
      { emoji: "📚", word: "library", ipa: "/ˈlaɪbrəri/", meaning: "thư viện" },
      { emoji: "🍴", word: "restaurant", ipa: "/ˈrestrɒnt/", meaning: "nhà hàng" },
      { emoji: "⛪", word: "church", ipa: "/tʃɜːtʃ/", meaning: "nhà thờ" },
      { emoji: "🏖️", word: "beach", ipa: "/biːtʃ/", meaning: "bãi biển" },
      { emoji: "🦁", word: "zoo", ipa: "/zuː/", meaning: "sở thú" },
      { emoji: "🏛️", word: "museum", ipa: "/mjuˈziːəm/", meaning: "bảo tàng" },
      { emoji: "🛫", word: "airport", ipa: "/ˈeəpɔːt/", meaning: "sân bay" },
      { emoji: "🏬", word: "market", ipa: "/ˈmɑːkɪt/", meaning: "chợ" },
      { emoji: "🎬", word: "cinema", ipa: "/ˈsɪnəmə/", meaning: "rạp chiếu phim" },
    ],
  },
  {
    id: 4, level: "Lớp 3", theme: "Thể thao", themeEn: "Sports",
    cards: [
      { emoji: "⚽", word: "football", ipa: "/ˈfʊtbɔːl/", meaning: "bóng đá" },
      { emoji: "🏀", word: "basketball", ipa: "/ˈbɑːskɪtbɔːl/", meaning: "bóng rổ" },
      { emoji: "🏐", word: "volleyball", ipa: "/ˈvɒlibɔːl/", meaning: "bóng chuyền" },
      { emoji: "🎾", word: "tennis", ipa: "/ˈtenɪs/", meaning: "quần vợt" },
      { emoji: "🏊", word: "swimming", ipa: "/ˈswɪmɪŋ/", meaning: "bơi lội" },
      { emoji: "🏃", word: "running", ipa: "/ˈrʌnɪŋ/", meaning: "chạy bộ" },
      { emoji: "🚴", word: "cycling", ipa: "/ˈsaɪklɪŋ/", meaning: "đạp xe" },
      { emoji: "🏸", word: "badminton", ipa: "/ˈbædmɪntən/", meaning: "cầu lông" },
      { emoji: "🏓", word: "table tennis", ipa: "/ˈteɪbl tenɪs/", meaning: "bóng bàn" },
      { emoji: "🥊", word: "boxing", ipa: "/ˈbɒksɪŋ/", meaning: "quyền anh" },
      { emoji: "⛸️", word: "skating", ipa: "/ˈskeɪtɪŋ/", meaning: "trượt băng" },
      { emoji: "🧗", word: "climbing", ipa: "/ˈklaɪmɪŋ/", meaning: "leo núi" },
      { emoji: "🏌️", word: "golf", ipa: "/ɡɒlf/", meaning: "gôn" },
      { emoji: "🤸", word: "gymnastics", ipa: "/dʒɪmˈnæstɪks/", meaning: "thể dục dụng cụ" },
    ],
  },
  {
    id: 5, level: "Lớp 3", theme: "Tính từ", themeEn: "Adjectives",
    cards: [
      { emoji: "🔼", word: "big", ipa: "/bɪɡ/", meaning: "to/lớn" },
      { emoji: "🔽", word: "small", ipa: "/smɔːl/", meaning: "nhỏ/bé" },
      { emoji: "📏", word: "tall", ipa: "/tɔːl/", meaning: "cao" },
      { emoji: "📐", word: "short", ipa: "/ʃɔːt/", meaning: "thấp/ngắn" },
      { emoji: "😀", word: "happy", ipa: "/ˈhæpi/", meaning: "vui vẻ" },
      { emoji: "😢", word: "sad", ipa: "/sæd/", meaning: "buồn" },
      { emoji: "⚡", word: "fast", ipa: "/fɑːst/", meaning: "nhanh" },
      { emoji: "🐢", word: "slow", ipa: "/sləʊ/", meaning: "chậm" },
      { emoji: "🔥", word: "hot", ipa: "/hɒt/", meaning: "nóng" },
      { emoji: "❄️", word: "cold", ipa: "/kəʊld/", meaning: "lạnh" },
      { emoji: "🆕", word: "new", ipa: "/njuː/", meaning: "mới" },
      { emoji: "📦", word: "old", ipa: "/əʊld/", meaning: "cũ/già" },
      { emoji: "💪", word: "strong", ipa: "/strɒŋ/", meaning: "khỏe/mạnh" },
      { emoji: "🧹", word: "clean", ipa: "/kliːn/", meaning: "sạch sẽ" },
    ],
  },
  {
    id: 6, level: "Lớp 3", theme: "Thiên nhiên", themeEn: "Nature",
    cards: [
      { emoji: "🌳", word: "tree", ipa: "/triː/", meaning: "cây" },
      { emoji: "🌸", word: "flower", ipa: "/ˈflaʊə/", meaning: "bông hoa" },
      { emoji: "🌿", word: "grass", ipa: "/ɡrɑːs/", meaning: "cỏ" },
      { emoji: "⛰️", word: "mountain", ipa: "/ˈmaʊntən/", meaning: "núi" },
      { emoji: "🌊", word: "sea", ipa: "/siː/", meaning: "biển" },
      { emoji: "🏞️", word: "river", ipa: "/ˈrɪvə/", meaning: "sông" },
      { emoji: "🌅", word: "sun", ipa: "/sʌn/", meaning: "mặt trời" },
      { emoji: "🌙", word: "moon", ipa: "/muːn/", meaning: "mặt trăng" },
      { emoji: "⭐", word: "star", ipa: "/stɑː/", meaning: "ngôi sao" },
      { emoji: "☁️", word: "cloud", ipa: "/klaʊd/", meaning: "mây" },
      { emoji: "🪨", word: "rock", ipa: "/rɒk/", meaning: "tảng đá" },
      { emoji: "🏝️", word: "island", ipa: "/ˈaɪlənd/", meaning: "hòn đảo" },
      { emoji: "🌲", word: "forest", ipa: "/ˈfɒrɪst/", meaning: "rừng" },
      { emoji: "🍃", word: "leaf", ipa: "/liːf/", meaning: "chiếc lá" },
    ],
  },
  {
    id: 7, level: "Lớp 3", theme: "Ngày tháng", themeEn: "Days & Months",
    cards: [
      { emoji: "📅", word: "Monday", ipa: "/ˈmʌndeɪ/", meaning: "thứ Hai" },
      { emoji: "📅", word: "Tuesday", ipa: "/ˈtjuːzdeɪ/", meaning: "thứ Ba" },
      { emoji: "📅", word: "Wednesday", ipa: "/ˈwenzdeɪ/", meaning: "thứ Tư" },
      { emoji: "📅", word: "Thursday", ipa: "/ˈθɜːzdeɪ/", meaning: "thứ Năm" },
      { emoji: "📅", word: "Friday", ipa: "/ˈfraɪdeɪ/", meaning: "thứ Sáu" },
      { emoji: "📅", word: "Saturday", ipa: "/ˈsætədeɪ/", meaning: "thứ Bảy" },
      { emoji: "📅", word: "Sunday", ipa: "/ˈsʌndeɪ/", meaning: "Chủ nhật" },
      { emoji: "🗓️", word: "week", ipa: "/wiːk/", meaning: "tuần" },
      { emoji: "🗓️", word: "month", ipa: "/mʌnθ/", meaning: "tháng" },
      { emoji: "🎆", word: "year", ipa: "/jɪə/", meaning: "năm" },
      { emoji: "☀️", word: "day", ipa: "/deɪ/", meaning: "ngày" },
      { emoji: "🌙", word: "night", ipa: "/naɪt/", meaning: "đêm" },
      { emoji: "🌷", word: "spring", ipa: "/sprɪŋ/", meaning: "mùa xuân" },
      { emoji: "🏖️", word: "summer", ipa: "/ˈsʌmə/", meaning: "mùa hè" },
    ],
  },
  // ===================== LỚP 4 =====================
  {
    id: 1, level: "Lớp 4", theme: "Động vật hoang dã", themeEn: "Wild Animals",
    cards: [
      { emoji: "🦒", word: "giraffe", ipa: "/dʒəˈrɑːf/", meaning: "hươu cao cổ" },
      { emoji: "🦓", word: "zebra", ipa: "/ˈzebrə/", meaning: "ngựa vằn" },
      { emoji: "🐆", word: "leopard", ipa: "/ˈlepəd/", meaning: "báo đốm" },
      { emoji: "🦏", word: "rhino", ipa: "/ˈraɪnəʊ/", meaning: "tê giác" },
      { emoji: "🦛", word: "hippo", ipa: "/ˈhɪpəʊ/", meaning: "hà mã" },
      { emoji: "🐊", word: "crocodile", ipa: "/ˈkrɒkədaɪl/", meaning: "cá sấu" },
      { emoji: "🐍", word: "snake", ipa: "/sneɪk/", meaning: "con rắn" },
      { emoji: "🦅", word: "eagle", ipa: "/ˈiːɡl/", meaning: "đại bàng" },
      { emoji: "🐺", word: "wolf", ipa: "/wʊlf/", meaning: "chó sói" },
      { emoji: "🦊", word: "fox", ipa: "/fɒks/", meaning: "cáo" },
      { emoji: "🦌", word: "deer", ipa: "/dɪə/", meaning: "hươu/nai" },
      { emoji: "🐒", word: "monkey", ipa: "/ˈmʌŋki/", meaning: "khỉ" },
      { emoji: "🦘", word: "kangaroo", ipa: "/ˌkæŋɡəˈruː/", meaning: "chuột túi" },
      { emoji: "🐧", word: "penguin", ipa: "/ˈpeŋɡwɪn/", meaning: "chim cánh cụt" },
    ],
  },
  {
    id: 2, level: "Lớp 4", theme: "Môn học", themeEn: "School Subjects",
    cards: [
      { emoji: "➗", word: "maths", ipa: "/mæθs/", meaning: "môn Toán" },
      { emoji: "📖", word: "English", ipa: "/ˈɪŋɡlɪʃ/", meaning: "môn Tiếng Anh" },
      { emoji: "🔬", word: "science", ipa: "/ˈsaɪəns/", meaning: "môn Khoa học" },
      { emoji: "🗺️", word: "geography", ipa: "/dʒiˈɒɡrəfi/", meaning: "môn Địa lí" },
      { emoji: "📜", word: "history", ipa: "/ˈhɪstri/", meaning: "môn Lịch sử" },
      { emoji: "🎨", word: "art", ipa: "/ɑːt/", meaning: "môn Mĩ thuật" },
      { emoji: "🎵", word: "music", ipa: "/ˈmjuːzɪk/", meaning: "môn Âm nhạc" },
      { emoji: "⚽", word: "PE", ipa: "/ˌpiː ˈiː/", meaning: "môn Thể dục" },
      { emoji: "💻", word: "computing", ipa: "/kəmˈpjuːtɪŋ/", meaning: "môn Tin học" },
      { emoji: "📝", word: "writing", ipa: "/ˈraɪtɪŋ/", meaning: "tập viết" },
      { emoji: "📚", word: "reading", ipa: "/ˈriːdɪŋ/", meaning: "tập đọc" },
      { emoji: "🧪", word: "chemistry", ipa: "/ˈkemɪstri/", meaning: "môn Hóa học" },
      { emoji: "🌍", word: "biology", ipa: "/baɪˈɒlədʒi/", meaning: "môn Sinh học" },
      { emoji: "🔔", word: "lesson", ipa: "/ˈlesn/", meaning: "bài học" },
    ],
  },
  {
    id: 3, level: "Lớp 4", theme: "Công nghệ", themeEn: "Technology",
    cards: [
      { emoji: "💻", word: "computer", ipa: "/kəmˈpjuːtə/", meaning: "máy tính" },
      { emoji: "📱", word: "phone", ipa: "/fəʊn/", meaning: "điện thoại" },
      { emoji: "⌨️", word: "keyboard", ipa: "/ˈkiːbɔːd/", meaning: "bàn phím" },
      { emoji: "🖱️", word: "mouse", ipa: "/maʊs/", meaning: "chuột máy tính" },
      { emoji: "🖥️", word: "screen", ipa: "/skriːn/", meaning: "màn hình" },
      { emoji: "🖨️", word: "printer", ipa: "/ˈprɪntə/", meaning: "máy in" },
      { emoji: "📷", word: "camera", ipa: "/ˈkæmrə/", meaning: "máy ảnh" },
      { emoji: "🎧", word: "headphones", ipa: "/ˈhedfəʊnz/", meaning: "tai nghe" },
      { emoji: "🔋", word: "battery", ipa: "/ˈbætri/", meaning: "pin" },
      { emoji: "🌐", word: "internet", ipa: "/ˈɪntənet/", meaning: "mạng internet" },
      { emoji: "📧", word: "email", ipa: "/ˈiːmeɪl/", meaning: "thư điện tử" },
      { emoji: "🤖", word: "robot", ipa: "/ˈrəʊbɒt/", meaning: "người máy" },
      { emoji: "🎮", word: "game", ipa: "/ɡeɪm/", meaning: "trò chơi điện tử" },
      { emoji: "💾", word: "file", ipa: "/faɪl/", meaning: "tệp tin" },
    ],
  },
  {
    id: 4, level: "Lớp 4", theme: "Cảm xúc", themeEn: "Emotions",
    cards: [
      { emoji: "😀", word: "happy", ipa: "/ˈhæpi/", meaning: "vui vẻ" },
      { emoji: "😢", word: "sad", ipa: "/sæd/", meaning: "buồn" },
      { emoji: "😠", word: "angry", ipa: "/ˈæŋɡri/", meaning: "tức giận" },
      { emoji: "😱", word: "scared", ipa: "/skeəd/", meaning: "sợ hãi" },
      { emoji: "😴", word: "tired", ipa: "/ˈtaɪəd/", meaning: "mệt mỏi" },
      { emoji: "😲", word: "surprised", ipa: "/səˈpraɪzd/", meaning: "ngạc nhiên" },
      { emoji: "😳", word: "shy", ipa: "/ʃaɪ/", meaning: "nhút nhát" },
      { emoji: "😎", word: "proud", ipa: "/praʊd/", meaning: "tự hào" },
      { emoji: "😟", word: "worried", ipa: "/ˈwʌrid/", meaning: "lo lắng" },
      { emoji: "😄", word: "excited", ipa: "/ɪkˈsaɪtɪd/", meaning: "hào hứng" },
      { emoji: "😐", word: "bored", ipa: "/bɔːd/", meaning: "chán" },
      { emoji: "😭", word: "upset", ipa: "/ʌpˈset/", meaning: "buồn bực" },
      { emoji: "🤗", word: "calm", ipa: "/kɑːm/", meaning: "bình tĩnh" },
      { emoji: "😊", word: "kind", ipa: "/kaɪnd/", meaning: "tử tế" },
    ],
  },
  {
    id: 5, level: "Lớp 4", theme: "Hoạt động hằng ngày", themeEn: "Daily Activities",
    cards: [
      { emoji: "⏰", word: "wake up", ipa: "/weɪk ʌp/", meaning: "thức dậy" },
      { emoji: "🪥", word: "brush teeth", ipa: "/brʌʃ tiːθ/", meaning: "đánh răng" },
      { emoji: "🚿", word: "take a shower", ipa: "/teɪk ə ˈʃaʊə/", meaning: "tắm" },
      { emoji: "🍳", word: "have breakfast", ipa: "/hæv ˈbrekfəst/", meaning: "ăn sáng" },
      { emoji: "🎒", word: "go to school", ipa: "/ɡəʊ tə skuːl/", meaning: "đi học" },
      { emoji: "📚", word: "study", ipa: "/ˈstʌdi/", meaning: "học bài" },
      { emoji: "🍱", word: "have lunch", ipa: "/hæv lʌntʃ/", meaning: "ăn trưa" },
      { emoji: "🏃", word: "play", ipa: "/pleɪ/", meaning: "chơi" },
      { emoji: "🍽️", word: "have dinner", ipa: "/hæv ˈdɪnə/", meaning: "ăn tối" },
      { emoji: "📺", word: "watch TV", ipa: "/wɒtʃ ˌtiː ˈviː/", meaning: "xem tivi" },
      { emoji: "🛏️", word: "go to bed", ipa: "/ɡəʊ tə bed/", meaning: "đi ngủ" },
      { emoji: "📖", word: "do homework", ipa: "/duː ˈhəʊmwɜːk/", meaning: "làm bài tập" },
      { emoji: "🧹", word: "clean the room", ipa: "/kliːn ðə ruːm/", meaning: "dọn phòng" },
      { emoji: "💤", word: "sleep", ipa: "/sliːp/", meaning: "ngủ" },
    ],
  },
  {
    id: 6, level: "Lớp 4", theme: "Môi trường", themeEn: "Environment",
    cards: [
      { emoji: "♻️", word: "recycle", ipa: "/ˌriːˈsaɪkl/", meaning: "tái chế" },
      { emoji: "🗑️", word: "rubbish", ipa: "/ˈrʌbɪʃ/", meaning: "rác" },
      { emoji: "🌍", word: "earth", ipa: "/ɜːθ/", meaning: "trái đất" },
      { emoji: "🌳", word: "plant", ipa: "/plɑːnt/", meaning: "trồng cây" },
      { emoji: "💧", word: "water", ipa: "/ˈwɔːtə/", meaning: "nước" },
      { emoji: "🌫️", word: "pollution", ipa: "/pəˈluːʃn/", meaning: "ô nhiễm" },
      { emoji: "🔆", word: "energy", ipa: "/ˈenədʒi/", meaning: "năng lượng" },
      { emoji: "🌱", word: "nature", ipa: "/ˈneɪtʃə/", meaning: "thiên nhiên" },
      { emoji: "🧴", word: "plastic", ipa: "/ˈplæstɪk/", meaning: "nhựa" },
      { emoji: "🌬️", word: "air", ipa: "/eə/", meaning: "không khí" },
      { emoji: "🚮", word: "bin", ipa: "/bɪn/", meaning: "thùng rác" },
      { emoji: "🌲", word: "forest", ipa: "/ˈfɒrɪst/", meaning: "rừng" },
      { emoji: "🧼", word: "clean", ipa: "/kliːn/", meaning: "sạch" },
      { emoji: "🐢", word: "protect", ipa: "/prəˈtekt/", meaning: "bảo vệ" },
    ],
  },
  {
    id: 7, level: "Lớp 4", theme: "Cơ thể nâng cao", themeEn: "Body — Advanced",
    cards: [
      { emoji: "🧠", word: "brain", ipa: "/breɪn/", meaning: "bộ não" },
      { emoji: "🫀", word: "heart", ipa: "/hɑːt/", meaning: "tim" },
      { emoji: "🫁", word: "lungs", ipa: "/lʌŋz/", meaning: "phổi" },
      { emoji: "🦴", word: "bone", ipa: "/bəʊn/", meaning: "xương" },
      { emoji: "🩸", word: "blood", ipa: "/blʌd/", meaning: "máu" },
      { emoji: "💪", word: "muscle", ipa: "/ˈmʌsl/", meaning: "cơ bắp" },
      { emoji: "👅", word: "tongue", ipa: "/tʌŋ/", meaning: "lưỡi" },
      { emoji: "🧴", word: "skin", ipa: "/skɪn/", meaning: "da" },
      { emoji: "😮", word: "throat", ipa: "/θrəʊt/", meaning: "cổ họng" },
      { emoji: "🦵", word: "knee", ipa: "/niː/", meaning: "đầu gối" },
      { emoji: "🦾", word: "elbow", ipa: "/ˈelbəʊ/", meaning: "khuỷu tay" },
      { emoji: "👄", word: "lip", ipa: "/lɪp/", meaning: "môi" },
      { emoji: "🧍", word: "shoulder", ipa: "/ˈʃəʊldə/", meaning: "vai" },
      { emoji: "⌚", word: "wrist", ipa: "/rɪst/", meaning: "cổ tay" },
    ],
  },
  // ===================== LỚP 5 =====================
  {
    id: 1, level: "Lớp 5", theme: "Thành phố", themeEn: "The City",
    cards: [
      { emoji: "🏙️", word: "city", ipa: "/ˈsɪti/", meaning: "thành phố" },
      { emoji: "🛣️", word: "street", ipa: "/striːt/", meaning: "đường phố" },
      { emoji: "🏢", word: "building", ipa: "/ˈbɪldɪŋ/", meaning: "tòa nhà" },
      { emoji: "🌉", word: "bridge", ipa: "/brɪdʒ/", meaning: "cây cầu" },
      { emoji: "🚦", word: "traffic light", ipa: "/ˈtræfɪk laɪt/", meaning: "đèn giao thông" },
      { emoji: "🅿️", word: "car park", ipa: "/ˈkɑː pɑːk/", meaning: "bãi đỗ xe" },
      { emoji: "🏨", word: "hotel", ipa: "/həʊˈtel/", meaning: "khách sạn" },
      { emoji: "🚇", word: "subway", ipa: "/ˈsʌbweɪ/", meaning: "tàu điện ngầm" },
      { emoji: "⛲", word: "square", ipa: "/skweə/", meaning: "quảng trường" },
      { emoji: "🚏", word: "bus stop", ipa: "/ˈbʌs stɒp/", meaning: "trạm xe buýt" },
      { emoji: "🏬", word: "mall", ipa: "/mɔːl/", meaning: "trung tâm thương mại" },
      { emoji: "🚶", word: "pavement", ipa: "/ˈpeɪvmənt/", meaning: "vỉa hè" },
      { emoji: "🏛️", word: "town hall", ipa: "/ˌtaʊn ˈhɔːl/", meaning: "tòa thị chính" },
      { emoji: "📍", word: "corner", ipa: "/ˈkɔːnə/", meaning: "góc phố" },
    ],
  },
  {
    id: 2, level: "Lớp 5", theme: "Khoa học", themeEn: "Science",
    cards: [
      { emoji: "🔬", word: "experiment", ipa: "/ɪkˈsperɪmənt/", meaning: "thí nghiệm" },
      { emoji: "🧲", word: "magnet", ipa: "/ˈmæɡnət/", meaning: "nam châm" },
      { emoji: "🌡️", word: "temperature", ipa: "/ˈtemprətʃə/", meaning: "nhiệt độ" },
      { emoji: "💡", word: "electricity", ipa: "/ɪˌlekˈtrɪsəti/", meaning: "điện" },
      { emoji: "🪐", word: "gravity", ipa: "/ˈɡrævəti/", meaning: "trọng lực" },
      { emoji: "🧪", word: "liquid", ipa: "/ˈlɪkwɪd/", meaning: "chất lỏng" },
      { emoji: "🧊", word: "solid", ipa: "/ˈsɒlɪd/", meaning: "chất rắn" },
      { emoji: "💨", word: "gas", ipa: "/ɡæs/", meaning: "chất khí" },
      { emoji: "⚛️", word: "atom", ipa: "/ˈætəm/", meaning: "nguyên tử" },
      { emoji: "🔆", word: "energy", ipa: "/ˈenədʒi/", meaning: "năng lượng" },
      { emoji: "🦠", word: "cell", ipa: "/sel/", meaning: "tế bào" },
      { emoji: "🪐", word: "planet", ipa: "/ˈplænɪt/", meaning: "hành tinh" },
      { emoji: "🔭", word: "telescope", ipa: "/ˈtelɪskəʊp/", meaning: "kính thiên văn" },
      { emoji: "➡️", word: "force", ipa: "/fɔːs/", meaning: "lực" },
    ],
  },
  {
    id: 3, level: "Lớp 5", theme: "Thế giới", themeEn: "The World",
    cards: [
      { emoji: "🌍", word: "world", ipa: "/wɜːld/", meaning: "thế giới" },
      { emoji: "🗺️", word: "country", ipa: "/ˈkʌntri/", meaning: "quốc gia" },
      { emoji: "🏳️", word: "flag", ipa: "/flæɡ/", meaning: "lá cờ" },
      { emoji: "🌎", word: "continent", ipa: "/ˈkɒntɪnənt/", meaning: "châu lục" },
      { emoji: "🌊", word: "ocean", ipa: "/ˈəʊʃn/", meaning: "đại dương" },
      { emoji: "🏜️", word: "desert", ipa: "/ˈdezət/", meaning: "sa mạc" },
      { emoji: "🏔️", word: "mountain", ipa: "/ˈmaʊntən/", meaning: "núi" },
      { emoji: "🗣️", word: "language", ipa: "/ˈlæŋɡwɪdʒ/", meaning: "ngôn ngữ" },
      { emoji: "🏙️", word: "capital", ipa: "/ˈkæpɪtl/", meaning: "thủ đô" },
      { emoji: "🧭", word: "map", ipa: "/mæp/", meaning: "bản đồ" },
      { emoji: "👥", word: "people", ipa: "/ˈpiːpl/", meaning: "con người" },
      { emoji: "🌏", word: "nation", ipa: "/ˈneɪʃn/", meaning: "dân tộc/quốc gia" },
      { emoji: "🕌", word: "culture", ipa: "/ˈkʌltʃə/", meaning: "văn hóa" },
      { emoji: "🚧", word: "border", ipa: "/ˈbɔːdə/", meaning: "biên giới" },
    ],
  },
  {
    id: 4, level: "Lớp 5", theme: "Động từ hành động", themeEn: "Action Verbs",
    cards: [
      { emoji: "🏃", word: "run", ipa: "/rʌn/", meaning: "chạy" },
      { emoji: "🚶", word: "walk", ipa: "/wɔːk/", meaning: "đi bộ" },
      { emoji: "🦘", word: "jump", ipa: "/dʒʌmp/", meaning: "nhảy" },
      { emoji: "🏊", word: "swim", ipa: "/swɪm/", meaning: "bơi" },
      { emoji: "✍️", word: "write", ipa: "/raɪt/", meaning: "viết" },
      { emoji: "📖", word: "read", ipa: "/riːd/", meaning: "đọc" },
      { emoji: "🗣️", word: "speak", ipa: "/spiːk/", meaning: "nói" },
      { emoji: "👂", word: "listen", ipa: "/ˈlɪsn/", meaning: "lắng nghe" },
      { emoji: "🤔", word: "think", ipa: "/θɪŋk/", meaning: "suy nghĩ" },
      { emoji: "🎨", word: "draw", ipa: "/drɔː/", meaning: "vẽ" },
      { emoji: "🛒", word: "buy", ipa: "/baɪ/", meaning: "mua" },
      { emoji: "🎁", word: "give", ipa: "/ɡɪv/", meaning: "cho/tặng" },
      { emoji: "🏗️", word: "build", ipa: "/bɪld/", meaning: "xây dựng" },
      { emoji: "🔧", word: "fix", ipa: "/fɪks/", meaning: "sửa chữa" },
    ],
  },
  {
    id: 5, level: "Lớp 5", theme: "Sức khỏe", themeEn: "Health",
    cards: [
      { emoji: "💪", word: "healthy", ipa: "/ˈhelθi/", meaning: "khỏe mạnh" },
      { emoji: "🤒", word: "sick", ipa: "/sɪk/", meaning: "bị ốm" },
      { emoji: "🤕", word: "headache", ipa: "/ˈhedeɪk/", meaning: "đau đầu" },
      { emoji: "🤧", word: "cold", ipa: "/kəʊld/", meaning: "cảm lạnh" },
      { emoji: "🌡️", word: "fever", ipa: "/ˈfiːvə/", meaning: "sốt" },
      { emoji: "💊", word: "medicine", ipa: "/ˈmedsn/", meaning: "thuốc" },
      { emoji: "🏃", word: "exercise", ipa: "/ˈeksəsaɪz/", meaning: "tập thể dục" },
      { emoji: "🥗", word: "diet", ipa: "/ˈdaɪət/", meaning: "chế độ ăn" },
      { emoji: "😴", word: "rest", ipa: "/rest/", meaning: "nghỉ ngơi" },
      { emoji: "🦷", word: "toothache", ipa: "/ˈtuːθeɪk/", meaning: "đau răng" },
      { emoji: "🩹", word: "hurt", ipa: "/hɜːt/", meaning: "bị thương/đau" },
      { emoji: "🧼", word: "wash", ipa: "/wɒʃ/", meaning: "rửa" },
      { emoji: "💧", word: "thirsty", ipa: "/ˈθɜːsti/", meaning: "khát nước" },
      { emoji: "🍎", word: "vitamin", ipa: "/ˈvɪtəmɪn/", meaning: "vitamin" },
    ],
  },
  {
    id: 6, level: "Lớp 5", theme: "Nghệ thuật", themeEn: "Arts",
    cards: [
      { emoji: "🎨", word: "painting", ipa: "/ˈpeɪntɪŋ/", meaning: "bức tranh" },
      { emoji: "🎵", word: "music", ipa: "/ˈmjuːzɪk/", meaning: "âm nhạc" },
      { emoji: "💃", word: "dance", ipa: "/dɑːns/", meaning: "nhảy múa" },
      { emoji: "🎭", word: "drama", ipa: "/ˈdrɑːmə/", meaning: "kịch" },
      { emoji: "🎬", word: "film", ipa: "/fɪlm/", meaning: "phim" },
      { emoji: "📸", word: "photography", ipa: "/fəˈtɒɡrəfi/", meaning: "nhiếp ảnh" },
      { emoji: "🎻", word: "violin", ipa: "/ˌvaɪəˈlɪn/", meaning: "đàn vi-ô-lông" },
      { emoji: "🎹", word: "piano", ipa: "/piˈænəʊ/", meaning: "đàn piano" },
      { emoji: "🥁", word: "drum", ipa: "/drʌm/", meaning: "cái trống" },
      { emoji: "🎤", word: "sing", ipa: "/sɪŋ/", meaning: "hát" },
      { emoji: "✏️", word: "sketch", ipa: "/sketʃ/", meaning: "phác họa" },
      { emoji: "🗿", word: "sculpture", ipa: "/ˈskʌlptʃə/", meaning: "tác phẩm điêu khắc" },
      { emoji: "🧑‍🎨", word: "artist", ipa: "/ˈɑːtɪst/", meaning: "nghệ sĩ" },
      { emoji: "🎫", word: "theatre", ipa: "/ˈθɪətə/", meaning: "nhà hát" },
    ],
  },
  {
    id: 7, level: "Lớp 5", theme: "Nghề nghiệp tương lai", themeEn: "Future Jobs",
    cards: [
      { emoji: "👨‍🔬", word: "scientist", ipa: "/ˈsaɪəntɪst/", meaning: "nhà khoa học" },
      { emoji: "👨‍🚀", word: "astronaut", ipa: "/ˈæstrənɔːt/", meaning: "phi hành gia" },
      { emoji: "👨‍💻", word: "programmer", ipa: "/ˈprəʊɡræmə/", meaning: "lập trình viên" },
      { emoji: "👨‍⚖️", word: "lawyer", ipa: "/ˈlɔːjə/", meaning: "luật sư" },
      { emoji: "👷", word: "engineer", ipa: "/ˌendʒɪˈnɪə/", meaning: "kĩ sư" },
      { emoji: "🧑‍🎨", word: "designer", ipa: "/dɪˈzaɪnə/", meaning: "nhà thiết kế" },
      { emoji: "📰", word: "journalist", ipa: "/ˈdʒɜːnəlɪst/", meaning: "nhà báo" },
      { emoji: "🧑‍🍳", word: "chef", ipa: "/ʃef/", meaning: "bếp trưởng" },
      { emoji: "🧑‍✈️", word: "pilot", ipa: "/ˈpaɪlət/", meaning: "phi công" },
      { emoji: "🎬", word: "director", ipa: "/dəˈrektə/", meaning: "đạo diễn" },
      { emoji: "🏛️", word: "architect", ipa: "/ˈɑːkɪtekt/", meaning: "kiến trúc sư" },
      { emoji: "💼", word: "businessman", ipa: "/ˈbɪznəsmæn/", meaning: "doanh nhân" },
      { emoji: "🔬", word: "researcher", ipa: "/rɪˈsɜːtʃə/", meaning: "nhà nghiên cứu" },
      { emoji: "🚀", word: "inventor", ipa: "/ɪnˈventə/", meaning: "nhà phát minh" },
    ],
  },
];

const data = { days: LESSONS };
window.data = data;

