// Học Tiếng Anh — Flashcard theo chủ đề
// Dữ liệu sinh từ bộ từ vựng tu-vung.md (21 chủ đề, không phân lớp).
// Mỗi card: { emoji, word, ipa, meaning }  — ipa để trống.

const LESSONS = [
  {
    id: 1, theme: "Màu sắc", themeEn: "Colours",
    cards: [
      { emoji: "🔴", word: "red", ipa: "", meaning: "màu đỏ" },
      { emoji: "🔵", word: "blue", ipa: "", meaning: "màu xanh dương" },
      { emoji: "🟡", word: "yellow", ipa: "", meaning: "màu vàng" },
      { emoji: "🟢", word: "green", ipa: "", meaning: "màu xanh lá" },
      { emoji: "🟠", word: "orange", ipa: "", meaning: "màu cam" },
      { emoji: "🩷", word: "pink", ipa: "", meaning: "màu hồng" },
      { emoji: "🟣", word: "purple", ipa: "", meaning: "màu tím" },
      { emoji: "🟤", word: "brown", ipa: "", meaning: "màu nâu" },
      { emoji: "⚫", word: "black", ipa: "", meaning: "màu đen" },
      { emoji: "⚪", word: "white", ipa: "", meaning: "màu trắng" },
      { emoji: "🩶", word: "grey", ipa: "", meaning: "màu xám" },
      { emoji: "🥇", word: "gold", ipa: "", meaning: "màu vàng kim" },
      { emoji: "🥈", word: "silver", ipa: "", meaning: "màu bạc" },
      { emoji: "🌤️", word: "light blue", ipa: "", meaning: "màu xanh nhạt" },
      { emoji: "🌲", word: "dark green", ipa: "", meaning: "màu xanh đậm" },
      { emoji: "🎨", word: "colour", ipa: "", meaning: "màu sắc" },
      { emoji: "🌈", word: "colourful", ipa: "", meaning: "nhiều màu sắc" },
      { emoji: "🌈", word: "rainbow", ipa: "", meaning: "cầu vồng" },
      { emoji: "✨", word: "bright", ipa: "", meaning: "sáng, rực rỡ" },
      { emoji: "🌑", word: "dark", ipa: "", meaning: "tối, sẫm" },
    ],
  },
  {
    id: 2, theme: "Động vật", themeEn: "Animals",
    cards: [
      { emoji: "🐱", word: "cat", ipa: "", meaning: "con mèo" },
      { emoji: "🐶", word: "dog", ipa: "", meaning: "con chó" },
      { emoji: "🐦", word: "bird", ipa: "", meaning: "con chim" },
      { emoji: "🐟", word: "fish", ipa: "", meaning: "con cá" },
      { emoji: "🐰", word: "rabbit", ipa: "", meaning: "con thỏ" },
      { emoji: "🦆", word: "duck", ipa: "", meaning: "con vịt" },
      { emoji: "🐔", word: "chicken", ipa: "", meaning: "con gà" },
      { emoji: "🐮", word: "cow", ipa: "", meaning: "con bò" },
      { emoji: "🐷", word: "pig", ipa: "", meaning: "con lợn" },
      { emoji: "🐴", word: "horse", ipa: "", meaning: "con ngựa" },
      { emoji: "🐑", word: "sheep", ipa: "", meaning: "con cừu" },
      { emoji: "🐐", word: "goat", ipa: "", meaning: "con dê" },
      { emoji: "🦁", word: "lion", ipa: "", meaning: "con sư tử" },
      { emoji: "🐯", word: "tiger", ipa: "", meaning: "con hổ" },
      { emoji: "🐘", word: "elephant", ipa: "", meaning: "con voi" },
      { emoji: "🐵", word: "monkey", ipa: "", meaning: "con khỉ" },
      { emoji: "🐻", word: "bear", ipa: "", meaning: "con gấu" },
      { emoji: "🦒", word: "giraffe", ipa: "", meaning: "con hươu cao cổ" },
      { emoji: "🦓", word: "zebra", ipa: "", meaning: "con ngựa vằn" },
      { emoji: "🐊", word: "crocodile", ipa: "", meaning: "con cá sấu" },
      { emoji: "🐍", word: "snake", ipa: "", meaning: "con rắn" },
      { emoji: "🐸", word: "frog", ipa: "", meaning: "con ếch" },
      { emoji: "🦋", word: "butterfly", ipa: "", meaning: "con bướm" },
      { emoji: "🐼", word: "panda", ipa: "", meaning: "con gấu trúc" },
    ],
  },
  {
    id: 3, theme: "Đồ chơi", themeEn: "Toys",
    cards: [
      { emoji: "⚽", word: "ball", ipa: "", meaning: "quả bóng" },
      { emoji: "🪆", word: "doll", ipa: "", meaning: "búp bê" },
      { emoji: "🚗", word: "car", ipa: "", meaning: "ô tô đồ chơi" },
      { emoji: "🧸", word: "teddy bear", ipa: "", meaning: "gấu bông" },
      { emoji: "🪁", word: "kite", ipa: "", meaning: "con diều" },
      { emoji: "🎈", word: "balloon", ipa: "", meaning: "bóng bay" },
      { emoji: "🚂", word: "train", ipa: "", meaning: "tàu hỏa đồ chơi" },
      { emoji: "✈️", word: "plane", ipa: "", meaning: "máy bay đồ chơi" },
      { emoji: "🤖", word: "robot", ipa: "", meaning: "người máy" },
      { emoji: "🧩", word: "puzzle", ipa: "", meaning: "trò xếp hình" },
      { emoji: "🧱", word: "blocks", ipa: "", meaning: "khối xếp hình" },
      { emoji: "🪀", word: "yo-yo", ipa: "", meaning: "con quay yo-yo" },
      { emoji: "🥁", word: "drum", ipa: "", meaning: "cái trống" },
      { emoji: "🌀", word: "top", ipa: "", meaning: "con quay" },
      { emoji: "🪢", word: "skipping rope", ipa: "", meaning: "dây nhảy" },
      { emoji: "🚙", word: "toy car", ipa: "", meaning: "xe đồ chơi" },
      { emoji: "🧱", word: "building blocks", ipa: "", meaning: "bộ lắp ghép" },
      { emoji: "🎲", word: "board game", ipa: "", meaning: "trò chơi bàn cờ" },
      { emoji: "🔵", word: "marbles", ipa: "", meaning: "bi (viên bi)" },
      { emoji: "📦", word: "toy box", ipa: "", meaning: "hộp đồ chơi" },
    ],
  },
  {
    id: 4, theme: "Trường học", themeEn: "School",
    cards: [
      { emoji: "🏫", word: "school", ipa: "", meaning: "trường học" },
      { emoji: "👩‍🏫", word: "class", ipa: "", meaning: "lớp học" },
      { emoji: "🚪", word: "classroom", ipa: "", meaning: "phòng học" },
      { emoji: "👨‍🏫", word: "teacher", ipa: "", meaning: "giáo viên" },
      { emoji: "🧑‍🎓", word: "student", ipa: "", meaning: "học sinh" },
      { emoji: "👫", word: "friend", ipa: "", meaning: "bạn bè" },
      { emoji: "🪑", word: "desk", ipa: "", meaning: "bàn học" },
      { emoji: "💺", word: "chair", ipa: "", meaning: "cái ghế" },
      { emoji: "📋", word: "board", ipa: "", meaning: "bảng" },
      { emoji: "🛝", word: "playground", ipa: "", meaning: "sân chơi" },
      { emoji: "📚", word: "library", ipa: "", meaning: "thư viện" },
      { emoji: "🚧", word: "gate", ipa: "", meaning: "cổng trường" },
      { emoji: "📖", word: "lesson", ipa: "", meaning: "bài học" },
      { emoji: "📝", word: "homework", ipa: "", meaning: "bài tập về nhà" },
      { emoji: "🗓️", word: "timetable", ipa: "", meaning: "thời khóa biểu" },
      { emoji: "📘", word: "subject", ipa: "", meaning: "môn học" },
      { emoji: "⏰", word: "break time", ipa: "", meaning: "giờ ra chơi" },
      { emoji: "👕", word: "uniform", ipa: "", meaning: "đồng phục" },
      { emoji: "🎒", word: "schoolbag", ipa: "", meaning: "cặp sách" },
      { emoji: "🧑‍💼", word: "headteacher", ipa: "", meaning: "hiệu trưởng" },
      { emoji: "🍽️", word: "canteen", ipa: "", meaning: "căng tin" },
    ],
  },
  {
    id: 5, theme: "Gia đình", themeEn: "Family",
    cards: [
      { emoji: "👨‍👩‍👧‍👦", word: "family", ipa: "", meaning: "gia đình" },
      { emoji: "👨", word: "father", ipa: "", meaning: "bố" },
      { emoji: "👩", word: "mother", ipa: "", meaning: "mẹ" },
      { emoji: "👦", word: "brother", ipa: "", meaning: "anh / em trai" },
      { emoji: "👧", word: "sister", ipa: "", meaning: "chị / em gái" },
      { emoji: "👶", word: "baby", ipa: "", meaning: "em bé" },
      { emoji: "👴", word: "grandfather", ipa: "", meaning: "ông" },
      { emoji: "👵", word: "grandmother", ipa: "", meaning: "bà" },
      { emoji: "👨‍👩‍👧", word: "parents", ipa: "", meaning: "bố mẹ" },
      { emoji: "👴👵", word: "grandparents", ipa: "", meaning: "ông bà" },
      { emoji: "👦", word: "son", ipa: "", meaning: "con trai" },
      { emoji: "👧", word: "daughter", ipa: "", meaning: "con gái" },
      { emoji: "🧔", word: "uncle", ipa: "", meaning: "chú / bác / cậu" },
      { emoji: "👩", word: "aunt", ipa: "", meaning: "cô / dì / bác gái" },
      { emoji: "🧑", word: "cousin", ipa: "", meaning: "anh chị em họ" },
      { emoji: "👦", word: "nephew", ipa: "", meaning: "cháu trai" },
      { emoji: "👧", word: "niece", ipa: "", meaning: "cháu gái" },
      { emoji: "🤵", word: "husband", ipa: "", meaning: "chồng" },
      { emoji: "👰", word: "wife", ipa: "", meaning: "vợ" },
      { emoji: "👪", word: "relatives", ipa: "", meaning: "họ hàng" },
    ],
  },
  {
    id: 6, theme: "Hình cơ bản", themeEn: "Shapes",
    cards: [
      { emoji: "⭕", word: "circle", ipa: "", meaning: "hình tròn" },
      { emoji: "🟦", word: "square", ipa: "", meaning: "hình vuông" },
      { emoji: "🔺", word: "triangle", ipa: "", meaning: "hình tam giác" },
      { emoji: "▭", word: "rectangle", ipa: "", meaning: "hình chữ nhật" },
      { emoji: "⭐", word: "star", ipa: "", meaning: "hình ngôi sao" },
      { emoji: "❤️", word: "heart", ipa: "", meaning: "hình trái tim" },
      { emoji: "🥚", word: "oval", ipa: "", meaning: "hình bầu dục" },
      { emoji: "🔷", word: "diamond", ipa: "", meaning: "hình thoi" },
      { emoji: "➖", word: "line", ipa: "", meaning: "đường thẳng" },
      { emoji: "⚫", word: "dot", ipa: "", meaning: "chấm tròn" },
      { emoji: "✝️", word: "cross", ipa: "", meaning: "hình chữ thập" },
      { emoji: "➡️", word: "arrow", ipa: "", meaning: "mũi tên" },
      { emoji: "🧊", word: "cube", ipa: "", meaning: "hình lập phương" },
      { emoji: "🔮", word: "sphere", ipa: "", meaning: "hình cầu" },
      { emoji: "🍦", word: "cone", ipa: "", meaning: "hình nón" },
      { emoji: "🥫", word: "cylinder", ipa: "", meaning: "hình trụ" },
      { emoji: "🔺", word: "pyramid", ipa: "", meaning: "hình chóp" },
      { emoji: "⬠", word: "pentagon", ipa: "", meaning: "hình ngũ giác" },
      { emoji: "⬡", word: "hexagon", ipa: "", meaning: "hình lục giác" },
      { emoji: "〰️", word: "curve", ipa: "", meaning: "đường cong" },
    ],
  },
  {
    id: 7, theme: "Địa điểm", themeEn: "Places",
    cards: [
      { emoji: "🏠", word: "home", ipa: "", meaning: "nhà" },
      { emoji: "🏫", word: "school", ipa: "", meaning: "trường học" },
      { emoji: "🏞️", word: "park", ipa: "", meaning: "công viên" },
      { emoji: "🏪", word: "shop", ipa: "", meaning: "cửa hàng" },
      { emoji: "🛒", word: "market", ipa: "", meaning: "chợ" },
      { emoji: "🦁", word: "zoo", ipa: "", meaning: "sở thú" },
      { emoji: "🏥", word: "hospital", ipa: "", meaning: "bệnh viện" },
      { emoji: "🏦", word: "bank", ipa: "", meaning: "ngân hàng" },
      { emoji: "🍽️", word: "restaurant", ipa: "", meaning: "nhà hàng" },
      { emoji: "🏬", word: "supermarket", ipa: "", meaning: "siêu thị" },
      { emoji: "📮", word: "post office", ipa: "", meaning: "bưu điện" },
      { emoji: "📚", word: "library", ipa: "", meaning: "thư viện" },
      { emoji: "🎬", word: "cinema", ipa: "", meaning: "rạp chiếu phim" },
      { emoji: "🏛️", word: "museum", ipa: "", meaning: "bảo tàng" },
      { emoji: "🏖️", word: "beach", ipa: "", meaning: "bãi biển" },
      { emoji: "🚜", word: "farm", ipa: "", meaning: "nông trại" },
      { emoji: "🚉", word: "station", ipa: "", meaning: "nhà ga" },
      { emoji: "🛫", word: "airport", ipa: "", meaning: "sân bay" },
      { emoji: "🚏", word: "bus stop", ipa: "", meaning: "trạm xe buýt" },
      { emoji: "🛝", word: "playground", ipa: "", meaning: "sân chơi" },
      { emoji: "🛕", word: "temple", ipa: "", meaning: "đền, chùa" },
      { emoji: "🏭", word: "factory", ipa: "", meaning: "nhà máy" },
    ],
  },
  {
    id: 8, theme: "Hoạt động hàng ngày", themeEn: "Daily activities",
    cards: [
      { emoji: "⏰", word: "get up", ipa: "", meaning: "thức dậy" },
      { emoji: "🧼", word: "wash my face", ipa: "", meaning: "rửa mặt" },
      { emoji: "🪥", word: "brush my teeth", ipa: "", meaning: "đánh răng" },
      { emoji: "🍳", word: "have breakfast", ipa: "", meaning: "ăn sáng" },
      { emoji: "👕", word: "get dressed", ipa: "", meaning: "mặc quần áo" },
      { emoji: "🎒", word: "go to school", ipa: "", meaning: "đi học" },
      { emoji: "🍱", word: "have lunch", ipa: "", meaning: "ăn trưa" },
      { emoji: "🏠", word: "go home", ipa: "", meaning: "về nhà" },
      { emoji: "📝", word: "do homework", ipa: "", meaning: "làm bài tập" },
      { emoji: "🍽️", word: "have dinner", ipa: "", meaning: "ăn tối" },
      { emoji: "🚿", word: "take a bath", ipa: "", meaning: "tắm" },
      { emoji: "📺", word: "watch TV", ipa: "", meaning: "xem ti vi" },
      { emoji: "📖", word: "read a book", ipa: "", meaning: "đọc sách" },
      { emoji: "🎮", word: "play games", ipa: "", meaning: "chơi trò chơi" },
      { emoji: "🤝", word: "help my mother", ipa: "", meaning: "giúp đỡ mẹ" },
      { emoji: "🛏️", word: "go to bed", ipa: "", meaning: "đi ngủ" },
      { emoji: "😴", word: "wake up", ipa: "", meaning: "tỉnh giấc" },
      { emoji: "💇", word: "comb my hair", ipa: "", meaning: "chải tóc" },
      { emoji: "🐱", word: "feed the cat", ipa: "", meaning: "cho mèo ăn" },
      { emoji: "🧹", word: "tidy my room", ipa: "", meaning: "dọn phòng" },
    ],
  },
  {
    id: 9, theme: "Hoạt động trong lớp học", themeEn: "Classroom activities",
    cards: [
      { emoji: "👂", word: "listen", ipa: "", meaning: "lắng nghe" },
      { emoji: "👀", word: "look", ipa: "", meaning: "nhìn" },
      { emoji: "📖", word: "read", ipa: "", meaning: "đọc" },
      { emoji: "✍️", word: "write", ipa: "", meaning: "viết" },
      { emoji: "🗣️", word: "speak", ipa: "", meaning: "nói" },
      { emoji: "🎤", word: "sing", ipa: "", meaning: "hát" },
      { emoji: "✏️", word: "draw", ipa: "", meaning: "vẽ" },
      { emoji: "🖍️", word: "colour", ipa: "", meaning: "tô màu" },
      { emoji: "👉", word: "point", ipa: "", meaning: "chỉ vào" },
      { emoji: "🔁", word: "repeat", ipa: "", meaning: "nhắc lại" },
      { emoji: "📕", word: "open your book", ipa: "", meaning: "mở sách" },
      { emoji: "📗", word: "close your book", ipa: "", meaning: "gấp sách" },
      { emoji: "🧍", word: "stand up", ipa: "", meaning: "đứng dậy" },
      { emoji: "🪑", word: "sit down", ipa: "", meaning: "ngồi xuống" },
      { emoji: "✋", word: "raise your hand", ipa: "", meaning: "giơ tay" },
      { emoji: "🤫", word: "be quiet", ipa: "", meaning: "giữ trật tự" },
      { emoji: "💬", word: "answer", ipa: "", meaning: "trả lời" },
      { emoji: "❓", word: "ask", ipa: "", meaning: "hỏi" },
      { emoji: "👥", word: "work in pairs", ipa: "", meaning: "làm việc theo cặp" },
      { emoji: "👨‍👩‍👧‍👦", word: "work in groups", ipa: "", meaning: "làm việc nhóm" },
      { emoji: "🙋", word: "come here", ipa: "", meaning: "lại đây" },
    ],
  },
  {
    id: 10, theme: "Đồ dùng học tập", themeEn: "School things",
    cards: [
      { emoji: "🖊️", word: "pen", ipa: "", meaning: "bút mực" },
      { emoji: "✏️", word: "pencil", ipa: "", meaning: "bút chì" },
      { emoji: "📕", word: "book", ipa: "", meaning: "quyển sách" },
      { emoji: "📓", word: "notebook", ipa: "", meaning: "vở" },
      { emoji: "📏", word: "ruler", ipa: "", meaning: "thước kẻ" },
      { emoji: "🧼", word: "rubber", ipa: "", meaning: "cục tẩy" },
      { emoji: "🎒", word: "bag", ipa: "", meaning: "cặp sách" },
      { emoji: "🖌️", word: "pencil case", ipa: "", meaning: "hộp bút" },
      { emoji: "🖍️", word: "crayon", ipa: "", meaning: "bút sáp màu" },
      { emoji: "🔪", word: "sharpener", ipa: "", meaning: "gọt bút chì" },
      { emoji: "🧴", word: "glue", ipa: "", meaning: "keo dán" },
      { emoji: "✂️", word: "scissors", ipa: "", meaning: "cái kéo" },
      { emoji: "📄", word: "paper", ipa: "", meaning: "giấy" },
      { emoji: "🖊️", word: "marker", ipa: "", meaning: "bút dạ" },
      { emoji: "🎨", word: "paint", ipa: "", meaning: "màu vẽ" },
      { emoji: "🖌️", word: "paintbrush", ipa: "", meaning: "cọ vẽ" },
      { emoji: "📁", word: "folder", ipa: "", meaning: "bìa kẹp hồ sơ" },
      { emoji: "🧮", word: "calculator", ipa: "", meaning: "máy tính bỏ túi" },
      { emoji: "📔", word: "dictionary", ipa: "", meaning: "từ điển" },
      { emoji: "📘", word: "textbook", ipa: "", meaning: "sách giáo khoa" },
    ],
  },
  {
    id: 11, theme: "Bộ phận cơ thể", themeEn: "Body parts",
    cards: [
      { emoji: "🗣️", word: "head", ipa: "", meaning: "cái đầu" },
      { emoji: "💇", word: "hair", ipa: "", meaning: "tóc" },
      { emoji: "😊", word: "face", ipa: "", meaning: "khuôn mặt" },
      { emoji: "👁️", word: "eye", ipa: "", meaning: "mắt" },
      { emoji: "👂", word: "ear", ipa: "", meaning: "tai" },
      { emoji: "👃", word: "nose", ipa: "", meaning: "mũi" },
      { emoji: "👄", word: "mouth", ipa: "", meaning: "miệng" },
      { emoji: "🦷", word: "teeth", ipa: "", meaning: "răng" },
      { emoji: "✋", word: "hand", ipa: "", meaning: "bàn tay" },
      { emoji: "💪", word: "arm", ipa: "", meaning: "cánh tay" },
      { emoji: "🦵", word: "leg", ipa: "", meaning: "chân" },
      { emoji: "🦶", word: "foot", ipa: "", meaning: "bàn chân" },
      { emoji: "👆", word: "finger", ipa: "", meaning: "ngón tay" },
      { emoji: "🦶", word: "toe", ipa: "", meaning: "ngón chân" },
      { emoji: "🤷", word: "shoulder", ipa: "", meaning: "vai" },
      { emoji: "🦵", word: "knee", ipa: "", meaning: "đầu gối" },
      { emoji: "🧣", word: "neck", ipa: "", meaning: "cổ" },
      { emoji: "🫃", word: "tummy", ipa: "", meaning: "bụng" },
      { emoji: "🔙", word: "back", ipa: "", meaning: "lưng" },
      { emoji: "👄", word: "lips", ipa: "", meaning: "đôi môi" },
    ],
  },
  {
    id: 12, theme: "Ngày trong tuần", themeEn: "Days of the week",
    cards: [
      { emoji: "1️⃣", word: "Monday", ipa: "", meaning: "thứ Hai" },
      { emoji: "2️⃣", word: "Tuesday", ipa: "", meaning: "thứ Ba" },
      { emoji: "3️⃣", word: "Wednesday", ipa: "", meaning: "thứ Tư" },
      { emoji: "4️⃣", word: "Thursday", ipa: "", meaning: "thứ Năm" },
      { emoji: "5️⃣", word: "Friday", ipa: "", meaning: "thứ Sáu" },
      { emoji: "6️⃣", word: "Saturday", ipa: "", meaning: "thứ Bảy" },
      { emoji: "7️⃣", word: "Sunday", ipa: "", meaning: "Chủ nhật" },
      { emoji: "☀️", word: "day", ipa: "", meaning: "ngày" },
      { emoji: "📅", word: "week", ipa: "", meaning: "tuần" },
      { emoji: "🎉", word: "weekend", ipa: "", meaning: "cuối tuần" },
      { emoji: "🗓️", word: "weekday", ipa: "", meaning: "ngày trong tuần (thường)" },
      { emoji: "📍", word: "today", ipa: "", meaning: "hôm nay" },
      { emoji: "⏭️", word: "tomorrow", ipa: "", meaning: "ngày mai" },
      { emoji: "⏮️", word: "yesterday", ipa: "", meaning: "hôm qua" },
      { emoji: "🌅", word: "morning", ipa: "", meaning: "buổi sáng" },
      { emoji: "🌤️", word: "afternoon", ipa: "", meaning: "buổi chiều" },
      { emoji: "🌆", word: "evening", ipa: "", meaning: "buổi tối" },
      { emoji: "🌙", word: "night", ipa: "", meaning: "ban đêm" },
      { emoji: "📆", word: "calendar", ipa: "", meaning: "lịch" },
      { emoji: "🔢", word: "date", ipa: "", meaning: "ngày tháng" },
    ],
  },
  {
    id: 13, theme: "Quần áo", themeEn: "Clothes",
    cards: [
      { emoji: "👔", word: "shirt", ipa: "", meaning: "áo sơ mi" },
      { emoji: "👕", word: "T-shirt", ipa: "", meaning: "áo phông" },
      { emoji: "👖", word: "trousers", ipa: "", meaning: "quần dài" },
      { emoji: "🩳", word: "shorts", ipa: "", meaning: "quần soóc" },
      { emoji: "👗", word: "skirt", ipa: "", meaning: "váy" },
      { emoji: "👗", word: "dress", ipa: "", meaning: "đầm, váy liền" },
      { emoji: "🧶", word: "jumper", ipa: "", meaning: "áo len chui đầu" },
      { emoji: "🧥", word: "jacket", ipa: "", meaning: "áo khoác" },
      { emoji: "🧥", word: "coat", ipa: "", meaning: "áo choàng" },
      { emoji: "🎩", word: "hat", ipa: "", meaning: "mũ" },
      { emoji: "🧢", word: "cap", ipa: "", meaning: "mũ lưỡi trai" },
      { emoji: "👟", word: "shoes", ipa: "", meaning: "giày" },
      { emoji: "🧦", word: "socks", ipa: "", meaning: "tất, vớ" },
      { emoji: "👡", word: "sandals", ipa: "", meaning: "dép quai hậu" },
      { emoji: "👢", word: "boots", ipa: "", meaning: "bốt, ủng" },
      { emoji: "🧤", word: "gloves", ipa: "", meaning: "găng tay" },
      { emoji: "🧣", word: "scarf", ipa: "", meaning: "khăn quàng cổ" },
      { emoji: "👖", word: "jeans", ipa: "", meaning: "quần bò" },
      { emoji: "👕", word: "uniform", ipa: "", meaning: "đồng phục" },
      { emoji: "🧥", word: "raincoat", ipa: "", meaning: "áo mưa" },
    ],
  },
  {
    id: 14, theme: "Phương tiện giao thông", themeEn: "Transport",
    cards: [
      { emoji: "🚗", word: "car", ipa: "", meaning: "ô tô" },
      { emoji: "🚌", word: "bus", ipa: "", meaning: "xe buýt" },
      { emoji: "🚲", word: "bike", ipa: "", meaning: "xe đạp" },
      { emoji: "🏍️", word: "motorbike", ipa: "", meaning: "xe máy" },
      { emoji: "🚂", word: "train", ipa: "", meaning: "tàu hỏa" },
      { emoji: "✈️", word: "plane", ipa: "", meaning: "máy bay" },
      { emoji: "⛵", word: "boat", ipa: "", meaning: "thuyền" },
      { emoji: "🚢", word: "ship", ipa: "", meaning: "tàu thủy" },
      { emoji: "🚕", word: "taxi", ipa: "", meaning: "xe taxi" },
      { emoji: "🚚", word: "truck", ipa: "", meaning: "xe tải" },
      { emoji: "🚐", word: "van", ipa: "", meaning: "xe tải nhỏ" },
      { emoji: "🚁", word: "helicopter", ipa: "", meaning: "máy bay trực thăng" },
      { emoji: "🚊", word: "tram", ipa: "", meaning: "tàu điện" },
      { emoji: "🚇", word: "underground", ipa: "", meaning: "tàu điện ngầm" },
      { emoji: "🛵", word: "scooter", ipa: "", meaning: "xe tay ga / xe scooter" },
      { emoji: "🚑", word: "ambulance", ipa: "", meaning: "xe cứu thương" },
      { emoji: "🚒", word: "fire engine", ipa: "", meaning: "xe cứu hỏa" },
      { emoji: "🚓", word: "police car", ipa: "", meaning: "xe cảnh sát" },
      { emoji: "⛴️", word: "ferry", ipa: "", meaning: "phà" },
      { emoji: "🚀", word: "rocket", ipa: "", meaning: "tên lửa" },
    ],
  },
  {
    id: 15, theme: "Hoạt động vui chơi", themeEn: "Free-time activities",
    cards: [
      { emoji: "⚽", word: "play football", ipa: "", meaning: "chơi bóng đá" },
      { emoji: "🏸", word: "play badminton", ipa: "", meaning: "chơi cầu lông" },
      { emoji: "🚲", word: "ride a bike", ipa: "", meaning: "đạp xe" },
      { emoji: "🏊", word: "swim", ipa: "", meaning: "bơi" },
      { emoji: "🏃", word: "run", ipa: "", meaning: "chạy" },
      { emoji: "🤸", word: "jump", ipa: "", meaning: "nhảy" },
      { emoji: "💃", word: "dance", ipa: "", meaning: "nhảy múa" },
      { emoji: "🎤", word: "sing", ipa: "", meaning: "hát" },
      { emoji: "🎨", word: "draw", ipa: "", meaning: "vẽ / tô màu" },
      { emoji: "📖", word: "read books", ipa: "", meaning: "đọc sách" },
      { emoji: "📺", word: "watch cartoons", ipa: "", meaning: "xem hoạt hình" },
      { emoji: "🎮", word: "play games", ipa: "", meaning: "chơi trò chơi" },
      { emoji: "🪁", word: "fly a kite", ipa: "", meaning: "thả diều" },
      { emoji: "🎧", word: "listen to music", ipa: "", meaning: "nghe nhạc" },
      { emoji: "🎣", word: "go fishing", ipa: "", meaning: "đi câu cá" },
      { emoji: "⛺", word: "go camping", ipa: "", meaning: "đi cắm trại" },
      { emoji: "📷", word: "take photos", ipa: "", meaning: "chụp ảnh" },
      { emoji: "⛸️", word: "skate", ipa: "", meaning: "trượt patin" },
      { emoji: "🎹", word: "play the piano", ipa: "", meaning: "chơi đàn piano" },
      { emoji: "🚶", word: "go for a walk", ipa: "", meaning: "đi dạo" },
    ],
  },
  {
    id: 16, theme: "Các phòng trong nhà", themeEn: "Rooms in the house",
    cards: [
      { emoji: "🛋️", word: "living room", ipa: "", meaning: "phòng khách" },
      { emoji: "🛏️", word: "bedroom", ipa: "", meaning: "phòng ngủ" },
      { emoji: "🍳", word: "kitchen", ipa: "", meaning: "nhà bếp" },
      { emoji: "🛁", word: "bathroom", ipa: "", meaning: "phòng tắm" },
      { emoji: "🍽️", word: "dining room", ipa: "", meaning: "phòng ăn" },
      { emoji: "🚽", word: "toilet", ipa: "", meaning: "nhà vệ sinh" },
      { emoji: "🚪", word: "hall", ipa: "", meaning: "sảnh, hành lang" },
      { emoji: "🚗", word: "garage", ipa: "", meaning: "nhà để xe" },
      { emoji: "🌷", word: "garden", ipa: "", meaning: "vườn" },
      { emoji: "🏡", word: "yard", ipa: "", meaning: "sân" },
      { emoji: "🚪", word: "door", ipa: "", meaning: "cửa ra vào" },
      { emoji: "🪟", word: "window", ipa: "", meaning: "cửa sổ" },
      { emoji: "🧱", word: "wall", ipa: "", meaning: "bức tường" },
      { emoji: "⬜", word: "floor", ipa: "", meaning: "sàn nhà" },
      { emoji: "🏠", word: "roof", ipa: "", meaning: "mái nhà" },
      { emoji: "🪜", word: "stairs", ipa: "", meaning: "cầu thang" },
      { emoji: "🏘️", word: "balcony", ipa: "", meaning: "ban công" },
      { emoji: "🏠", word: "attic", ipa: "", meaning: "gác mái" },
      { emoji: "📚", word: "study", ipa: "", meaning: "phòng làm việc / học" },
      { emoji: "🚧", word: "gate", ipa: "", meaning: "cổng" },
    ],
  },
  {
    id: 17, theme: "Các loại quả", themeEn: "Fruits",
    cards: [
      { emoji: "🍎", word: "apple", ipa: "", meaning: "quả táo" },
      { emoji: "🍌", word: "banana", ipa: "", meaning: "quả chuối" },
      { emoji: "🍊", word: "orange", ipa: "", meaning: "quả cam" },
      { emoji: "🥭", word: "mango", ipa: "", meaning: "quả xoài" },
      { emoji: "🍇", word: "grape", ipa: "", meaning: "quả nho" },
      { emoji: "🍉", word: "watermelon", ipa: "", meaning: "quả dưa hấu" },
      { emoji: "🍓", word: "strawberry", ipa: "", meaning: "quả dâu tây" },
      { emoji: "🍍", word: "pineapple", ipa: "", meaning: "quả dứa" },
      { emoji: "🍋", word: "lemon", ipa: "", meaning: "quả chanh vàng" },
      { emoji: "🫑", word: "papaya", ipa: "", meaning: "quả đu đủ" },
      { emoji: "🥥", word: "coconut", ipa: "", meaning: "quả dừa" },
      { emoji: "🍐", word: "guava", ipa: "", meaning: "quả ổi" },
      { emoji: "🍐", word: "pear", ipa: "", meaning: "quả lê" },
      { emoji: "🍑", word: "peach", ipa: "", meaning: "quả đào" },
      { emoji: "🍒", word: "cherry", ipa: "", meaning: "quả anh đào" },
      { emoji: "🔴", word: "lychee", ipa: "", meaning: "quả vải" },
      { emoji: "🟤", word: "longan", ipa: "", meaning: "quả nhãn" },
      { emoji: "🐉", word: "dragon fruit", ipa: "", meaning: "quả thanh long" },
      { emoji: "🟢", word: "jackfruit", ipa: "", meaning: "quả mít" },
      { emoji: "⭐", word: "star fruit", ipa: "", meaning: "quả khế" },
    ],
  },
  {
    id: 18, theme: "Thức ăn", themeEn: "Food",
    cards: [
      { emoji: "🍚", word: "rice", ipa: "", meaning: "cơm / gạo" },
      { emoji: "🍞", word: "bread", ipa: "", meaning: "bánh mì" },
      { emoji: "🍜", word: "noodles", ipa: "", meaning: "mì, bún" },
      { emoji: "🐟", word: "fish", ipa: "", meaning: "cá" },
      { emoji: "🍖", word: "meat", ipa: "", meaning: "thịt" },
      { emoji: "🍗", word: "chicken", ipa: "", meaning: "thịt gà" },
      { emoji: "🥚", word: "egg", ipa: "", meaning: "trứng" },
      { emoji: "🥛", word: "milk", ipa: "", meaning: "sữa" },
      { emoji: "🧀", word: "cheese", ipa: "", meaning: "phô mai" },
      { emoji: "🍲", word: "soup", ipa: "", meaning: "súp, canh" },
      { emoji: "🥦", word: "vegetables", ipa: "", meaning: "rau củ" },
      { emoji: "🍓", word: "fruit", ipa: "", meaning: "hoa quả" },
      { emoji: "🍰", word: "cake", ipa: "", meaning: "bánh ngọt" },
      { emoji: "🥪", word: "sandwich", ipa: "", meaning: "bánh mì kẹp" },
      { emoji: "🍔", word: "hamburger", ipa: "", meaning: "bánh mì kẹp thịt" },
      { emoji: "🍕", word: "pizza", ipa: "", meaning: "bánh pizza" },
      { emoji: "🍦", word: "ice cream", ipa: "", meaning: "kem" },
      { emoji: "🍫", word: "chocolate", ipa: "", meaning: "sô cô la" },
      { emoji: "🥗", word: "salad", ipa: "", meaning: "rau trộn" },
      { emoji: "💧", word: "water", ipa: "", meaning: "nước" },
      { emoji: "🧃", word: "juice", ipa: "", meaning: "nước ép" },
      { emoji: "🌭", word: "sausage", ipa: "", meaning: "xúc xích" },
    ],
  },
  {
    id: 19, theme: "Cảm xúc", themeEn: "Feelings",
    cards: [
      { emoji: "😄", word: "happy", ipa: "", meaning: "vui vẻ" },
      { emoji: "😢", word: "sad", ipa: "", meaning: "buồn" },
      { emoji: "😠", word: "angry", ipa: "", meaning: "tức giận" },
      { emoji: "😫", word: "tired", ipa: "", meaning: "mệt mỏi" },
      { emoji: "🍽️", word: "hungry", ipa: "", meaning: "đói" },
      { emoji: "🥤", word: "thirsty", ipa: "", meaning: "khát" },
      { emoji: "😨", word: "scared", ipa: "", meaning: "sợ hãi" },
      { emoji: "🤩", word: "excited", ipa: "", meaning: "hào hứng" },
      { emoji: "😑", word: "bored", ipa: "", meaning: "chán" },
      { emoji: "😲", word: "surprised", ipa: "", meaning: "ngạc nhiên" },
      { emoji: "😴", word: "sleepy", ipa: "", meaning: "buồn ngủ" },
      { emoji: "😳", word: "shy", ipa: "", meaning: "nhút nhát" },
      { emoji: "😟", word: "worried", ipa: "", meaning: "lo lắng" },
      { emoji: "😌", word: "proud", ipa: "", meaning: "tự hào" },
      { emoji: "😬", word: "nervous", ipa: "", meaning: "hồi hộp" },
      { emoji: "😌", word: "calm", ipa: "", meaning: "bình tĩnh" },
      { emoji: "🤒", word: "sick", ipa: "", meaning: "ốm, bệnh" },
      { emoji: "🥶", word: "cold", ipa: "", meaning: "lạnh" },
      { emoji: "🥵", word: "hot", ipa: "", meaning: "nóng" },
      { emoji: "🙂", word: "fine", ipa: "", meaning: "khỏe, ổn" },
    ],
  },
  {
    id: 20, theme: "Giác quan", themeEn: "Senses",
    cards: [
      { emoji: "👁️", word: "sight", ipa: "", meaning: "thị giác" },
      { emoji: "👂", word: "hearing", ipa: "", meaning: "thính giác" },
      { emoji: "👃", word: "smell", ipa: "", meaning: "khứu giác" },
      { emoji: "👅", word: "taste", ipa: "", meaning: "vị giác" },
      { emoji: "✋", word: "touch", ipa: "", meaning: "xúc giác" },
      { emoji: "👀", word: "see", ipa: "", meaning: "nhìn, thấy" },
      { emoji: "🦻", word: "hear", ipa: "", meaning: "nghe" },
      { emoji: "🌸", word: "smell", ipa: "", meaning: "ngửi" },
      { emoji: "🍬", word: "taste", ipa: "", meaning: "nếm" },
      { emoji: "🤚", word: "touch", ipa: "", meaning: "chạm, sờ" },
      { emoji: "👁️", word: "eye", ipa: "", meaning: "mắt" },
      { emoji: "👂", word: "ear", ipa: "", meaning: "tai" },
      { emoji: "👃", word: "nose", ipa: "", meaning: "mũi" },
      { emoji: "👅", word: "tongue", ipa: "", meaning: "lưỡi" },
      { emoji: "🫳", word: "skin", ipa: "", meaning: "da" },
      { emoji: "🔊", word: "loud", ipa: "", meaning: "to (âm thanh)" },
      { emoji: "🔇", word: "quiet", ipa: "", meaning: "yên tĩnh" },
      { emoji: "🍭", word: "sweet", ipa: "", meaning: "ngọt" },
      { emoji: "🍋", word: "sour", ipa: "", meaning: "chua" },
      { emoji: "☁️", word: "soft", ipa: "", meaning: "mềm" },
      { emoji: "🪨", word: "hard", ipa: "", meaning: "cứng" },
    ],
  },
  {
    id: 21, theme: "Trò chơi", themeEn: "Games",
    cards: [
      { emoji: "🙈", word: "hide-and-seek", ipa: "", meaning: "trốn tìm" },
      { emoji: "🏃", word: "tag", ipa: "", meaning: "đuổi bắt" },
      { emoji: "🦶", word: "hopscotch", ipa: "", meaning: "nhảy lò cò" },
      { emoji: "🪢", word: "tug of war", ipa: "", meaning: "kéo co" },
      { emoji: "🤸", word: "skipping", ipa: "", meaning: "nhảy dây" },
      { emoji: "🪑", word: "musical chairs", ipa: "", meaning: "trò giành ghế" },
      { emoji: "🧩", word: "puzzle", ipa: "", meaning: "xếp hình" },
      { emoji: "🎲", word: "board game", ipa: "", meaning: "trò chơi bàn cờ" },
      { emoji: "♟️", word: "chess", ipa: "", meaning: "cờ vua" },
      { emoji: "🃏", word: "card game", ipa: "", meaning: "trò chơi bài" },
      { emoji: "🧩", word: "jigsaw", ipa: "", meaning: "trò ghép tranh" },
      { emoji: "🐐", word: "blind man's buff", ipa: "", meaning: "bịt mắt bắt dê" },
      { emoji: "🔵", word: "marbles", ipa: "", meaning: "bắn bi" },
      { emoji: "🤾", word: "catch", ipa: "", meaning: "trò bắt bóng" },
      { emoji: "🎮", word: "video game", ipa: "", meaning: "trò chơi điện tử" },
      { emoji: "❓", word: "quiz", ipa: "", meaning: "trò đố vui" },
      { emoji: "🎭", word: "role play", ipa: "", meaning: "đóng vai" },
      { emoji: "🤔", word: "guessing game", ipa: "", meaning: "trò đoán" },
      { emoji: "🁢", word: "dominoes", ipa: "", meaning: "trò domino" },
      { emoji: "✊", word: "rock-paper-scissors", ipa: "", meaning: "oẳn tù tì" },
    ],
  },
];

const data = { days: LESSONS };
window.data = data;
